// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63q-qfUq3bgEpz2VLBec48h1L2YGqX-s',
    appId: '1:241696567632:web:bd718001ccd751b03bfc55',
    messagingSenderId: '241696567632',
    projectId: 'nanumi-df9e4',
    authDomain: 'nanumi-df9e4.firebaseapp.com',
    storageBucket: 'nanumi-df9e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfVbFB-w6srBhmmQiDOGI02FbyKOCBlek',
    appId: '1:241696567632:android:b6c7c10c69efcb363bfc55',
    messagingSenderId: '241696567632',
    projectId: 'nanumi-df9e4',
    storageBucket: 'nanumi-df9e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAYsTVuQk1OJpzBarW4z3YOEwu8TG8sQ',
    appId: '1:241696567632:ios:56b287f8bf9bf4643bfc55',
    messagingSenderId: '241696567632',
    projectId: 'nanumi-df9e4',
    storageBucket: 'nanumi-df9e4.appspot.com',
    iosClientId:
        '241696567632-o1opb538qlkt3jnof7a4q4sah3mh8rkn.apps.googleusercontent.com',
    iosBundleId: 'com.parrottkim.nanumi',
  );
}
